// client/src/components/profileImage.vue
<template>
  <div v-if="user.image?.includes('profile_image')" class="d-flex justify-center mb-5">
    <img :src="imageSrc + user.image" class="user-profile-image rounded-circle"
      style="width:70px; height:70px;" />
  </div>

  <div v-else>
    <v-avatar :color="user.image" size="50" class="d-flex mx-auto mt-5 mb-3">
      <span class="text-h5 text-uppercase">{{ avatar }}</span>
    </v-avatar>
  </div>
</template>

<script lang="ts">
import { computed } from 'vue';


export default {
  name: 'profileImage',
  props: ["user"],

  setup(props) {
    const imageSrc = window.env.SERVER_DOMAIN_NAME_API.replace("api", "")
    const avatar = computed(() => {
      if (props.user.full_name) {
        let val = String(props.user.full_name);
        return val.charAt(0);
      }
      return props.user.email?.charAt(0) + props.user.email?.charAt(1);
    });


    return {
      avatar,
      imageSrc,
    }
  }
}
</script>

// client/src/components/profile/ProfileImage.svelte
<script lang="ts">
    import type {
        UserInterface,
    } from '../../types';
    export let user: UserInterface|undefined;
    export let size: number = 50;

    let username: string[];
    let logo: string;

    if(user){
        if (user.full_name.split(' ')[0] == ""){
            logo = `${user.email[0].toLocaleUpperCase()}${user.email[1].toLocaleUpperCase()}`
        } else {
            username = user.full_name.split(' ')
            logo = `${username[0][0].toLocaleUpperCase()}${username[1][0].toLocaleUpperCase()}`
        }
    }

</script>

{#if user}
    <a href='/profile/{user.id}'>
        {#if user.image.includes("profile_image") }
            <!-- svelte-ignore a11y-missing-attribute -->
            <img
                src="{process.env.APP_BASE_API_URL + user.image.replace('/', '')}"
                class="user-profile-image rounded-circle"
                style="width:{size}px; height:{size}px;"
            />
        {:else}
            <span class="user-profile-image rounded-circle"
                style="background-color:{user.image}; width:{size}px; height:{size}px;"
            >
                {logo}
            </span>
        {/if}
    </a>
{/if}

<style>
    .user-profile-image{
        color: #fff;
        font-weight: 700;
        justify-content: center;
        align-items: center;
        display: flex;
        border-radius: 50px
    }
</style>
