// client/src/components/vacationBalance.vue
<template>
  <v-card>
    <v-card-title class="font-weight-bold bg-primary">Vacation Balance</v-card-title>
    <v-row class="text-center mt-2 mb-0">
      <v-col v-for="header in vacationInfoHeaders" :key="header">
        <h4>{{ header }}</h4>
      </v-col>
    </v-row>
    <v-row class="text-center mt-0 mb-2">
      <v-col>
        {{ balance ? balance[0]?.annual_leaves.reserved : "--" }} / {{ balance ? balance[0]?.annual_leaves.all : "--" }}
      </v-col>
      <v-col>
        {{ balance ? balance[0]?.emergency_leaves.reserved : "--" }} / {{ balance ? balance[0]?.emergency_leaves.all : "--"
        }}
      </v-col>
      <v-col>
        {{ balance ? balance[0]?.leave_excuses.reserved : "--" }} / {{ balance ? balance[0]?.leave_excuses.all : "--" }}
      </v-col>
    </v-row>
  </v-card>
</template>

<script lang="ts">
export default {
  name: 'vacationBalance',
  props: ['balance'],

  setup(props) {
    const vacationInfoHeaders = ['Annuals', 'Emergencies', 'Excuses']

    return {
      vacationInfoHeaders
    }
  }
}
</script>

// client/src/componants/profile/VacationBalance.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import Vacation from "../../apis/vacations/Vacation";
  import type { VacationBalance } from "../../utils/types";

  export let user: any;

  let balance: VacationBalance;

  onMount(async () => {
    balance = await Vacation.balance(user.id);
  });
</script>

{#if balance != null}
  <div class="card">
    <div class="card-header">Vacation Balance</div>
    <div class="card-body">
      <div class="row">
        <div class="col-4 text-muted d-flex justify-content-center">Annuals</div>
        <div class="col-4 text-muted d-flex justify-content-center">Emergencies</div>
        <div class="col-4 text-muted d-flex justify-content-center">Excuses</div>
      </div>
      <div class="row">
        <div class="col-4 text-muted d-flex justify-content-center">
          {balance.annual_leaves.reserved} / {balance.annual_leaves.all}
        </div>
        <div class="col-4 text-muted d-flex justify-content-center">
          {balance.emergency_leaves.reserved} / {balance.emergency_leaves.all}
        </div>
        <div class="col-4 text-muted d-flex justify-content-center">
          {balance.leave_excuses.reserved} / {balance.leave_excuses.all}
        </div>
      </div>
    </div>
  </div>
{/if}
