// client/src/components/profile/VacationBalance.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import Vacation from '../../services/axios/vacations/Vacation';

    let vacationBalance: any = null;
    onMount(async () => {
        vacationBalance = await Vacation.balance();
    });
</script>

{#if vacationBalance != null}
    <div class="card">
        <div class="card-header">Vacation Balance</div>
        <div class="card-body">
        <div class="row">
            <div class="col-3 text-muted d-flex justify-content-center">Annuals</div>
            <div class="col-3 text-muted d-flex justify-content-center">Emergencies</div>
            <div class="col-3 text-muted d-flex justify-content-center">Excuses</div>
            <div class="col-3 text-muted d-flex justify-content-center">Public</div>
        </div>
        <div class="row">
            <div class="col-3 text-muted d-flex justify-content-center">{vacationBalance.annual_leaves}</div>
            <div class="col-3 text-muted d-flex justify-content-center">{vacationBalance.emergency_leaves}</div>
            <div class="col-3 text-muted d-flex justify-content-center">{vacationBalance.leave_excuses}</div>
            <div class="col-3 text-muted d-flex justify-content-center">{vacationBalance.public_holidays}</div>
        </div>
        </div>
    </div>
{/if}

// client/src/components/vacationBalance.vue
<template>
  <v-card>
    <v-card-title class="font-weight-bold bg-primary">Vacation Balance</v-card-title>
    <v-row class="text-center mt-2 mb-0">
      <v-col v-for="header in vacationInfoHeaders" :key="header">
        <h4>{{ header }}</h4>
      </v-col>
    </v-row>
    <v-row class="text-center mt-0 mb-2">
      <v-col>
        {{ balance ? balance[0]?.annual_leaves.reserved : "--" }} / {{ balance ? balance[0]?.annual_leaves.all : "--" }}
      </v-col>
      <v-col>
        {{ balance ? balance[0]?.emergency_leaves.reserved : "--" }} / {{ balance ? balance[0]?.emergency_leaves.all : "--"
        }}
      </v-col>
      <v-col>
        {{ balance ? balance[0]?.leave_excuses.reserved : "--" }} / {{ balance ? balance[0]?.leave_excuses.all : "--" }}
      </v-col>
    </v-row>
  </v-card>
</template>

<script lang="ts">
export default {
  name: 'vacationBalance',
  props: ['balance'],

  setup(props) {
    const vacationInfoHeaders = ['Annuals', 'Emergencies', 'Excuses']

    return {
      vacationInfoHeaders
    }
  }
}
</script>
